age = int(input("Please tell me your age: "))
print(f"Your are currently {age} years old.")
print(f"In 10 years, you'll be {age+10} years old.")
print(f"In 20 years, you'll be {age+20} yeras old.")
print(f"In 30 years, you'll be {age+30} yeras old.")
